### ISSUE TITLE
servlet-api 3.0

### ISSUE THREAD

**Issue by glassfishrobot** [eclipse-ee4j/glassfish-grizzly#1383]
hi,
in fedora we cant use servlet-api 2.5 for import new package (servlet-api 3.1 is unavailable and i think isnt possible use or import this library)
we have servlet-api provides by tomcat 7.x and org.jboss.spec.javax.servlet jboss-servlet-api_3.0_spec
this is the build error

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7:27.968s
[INFO] Finished at: Fri Dec 14 11:44:11 CET 2012
[INFO] Final Memory: 27M/302M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project grizzly-http-servlet: Compilation failure: Compilation failure:
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.2.19/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/WebappContext.java:[123,7] error: WebappContext is not abstract and does not override abstract method getJspConfigDescriptor() in ServletContext
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.2.19/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/WebappContext.java:[712,52] error: getFilterRegistrations() in WebappContext cannot implement getFilterRegistrations() in ServletContext
[ERROR] return type Map<String,? extends org.glassfish.grizzly.servlet.FilterRegistration> is not compatible with Map<String,? extends javax.servlet.FilterRegistration>
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.2.19/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/WebappContext.java:[688,30] error: getFilterRegistration(String) in WebappContext cannot implement getFilterRegistration(String) in ServletContext
[ERROR] return type org.glassfish.grizzly.servlet.FilterRegistration is not compatible with javax.servlet.FilterRegistration
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.2.19/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/WebappContext.java:[383,30] error: addFilter(String,Class<? extends Filter>) in WebappContext cannot implement addFilter(String,Class<? extends Filter>) in ServletContext
[ERROR] return type FilterRegistration is not compatible with Dynamic
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.2.19/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/WebappContext.java:[437,30] error: addFilter(String,Filter) in WebappContext cannot implement addFilter(String,Filter) in ServletContext
[ERROR] return type FilterRegistration is not compatible with Dynamic
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.2.19/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/WebappContext.java:[490,30] error: addFilter(String,String) in WebappContext cannot implement addFilter(String,String) in ServletContext
[ERROR] return type FilterRegistration is not compatible with Dynamic
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.2.19/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/WebappContext.java:[750,53] error: getServletRegistrations() in WebappContext cannot implement getServletRegistrations() in ServletContext
[ERROR] return type Map<String,? extends org.glassfish.grizzly.servlet.ServletRegistration> is not compatible with Map<String,? extends javax.servlet.ServletRegistration>
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.2.19/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/WebappContext.java:[724,31] error: getServletRegistration(String) in WebappContext cannot implement getServletRegistration(String) in ServletContext
[ERROR] return type org.glassfish.grizzly.servlet.ServletRegistration is not compatible with javax.servlet.ServletRegistration
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.2.19/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/WebappContext.java:[542,31] error: addServlet(String,Class<? extends Servlet>) in WebappContext cannot implement addServlet(String,Class<? extends Servlet>) in ServletContext
[ERROR] return type ServletRegistration is not compatible with Dynamic
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.2.19/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/WebappContext.java:[597,31] error: addServlet(String,Servlet) in WebappContext cannot implement addServlet(String,Servlet) in ServletContext
[ERROR] return type ServletRegistration is not compatible with Dynamic
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.2.19/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/WebappContext.java:[654,31] error: addServlet(String,String) in WebappContext cannot implement addServlet(String,String) in ServletContext
[ERROR] return type requires unchecked conversion from Enumeration to Enumeration<String>
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.2.19/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/HttpServletRequestImpl.java:[96,7] error: HttpServletRequestImpl is not abstract and does not override abstract method getPart(String) in HttpServletRequest
[ERROR] return type requires unchecked conversion from Enumeration to Enumeration<String>
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.2.19/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/HttpServletResponseImpl.java:[85,7] error: HttpServletResponseImpl is not abstract and does not override abstract method getHeaderNames() in HttpServletResponse

thanks in advance for every help
regards
#### Environment
fedora all version
java version "1.7.0_09-icedtea"
OpenJDK Runtime Environment (fedora-2.3.3.2.fc18-i386)
OpenJDK Server VM (build 23.2-b09, mixed mode)
#### Affected Versions
[2.2.19]

**Comment by glassfishrobot** [comment]
@glassfishrobot Commented 
Reported by puntogil

**Comment by glassfishrobot** [comment]
@glassfishrobot Commented 
Was assigned to oleksiys

**Comment by glassfishrobot** [comment]
@glassfishrobot Commented 
oleksiys said:
Hello,

we're planning to release 2.3 version soon, can you pls. check if what you want works with 2.3-beta8.

thanks!

**Comment by glassfishrobot** [comment]
@glassfishrobot Commented 
puntogil said:
hi
i tried to build grizzly 2.3-beta8 with org.apache.tomcat tomcat-servlet-api 7.0.33

the result

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project grizzly-http-servlet: Compilation failure: Compilation failure:
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/HttpServletRequestImpl.java:[89,25] error: cannot find symbol
[ERROR] symbol: class ProtocolHandler
[ERROR] location: package javax.servlet.http
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletInputStreamImpl.java:[61,20] error: cannot find symbol
[ERROR] symbol: class ReadListener
[ERROR] location: package javax.servlet
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/HttpServletRequestImpl.java:[1588,24] error: cannot find symbol
[ERROR] symbol: class ProtocolHandler
[ERROR] location: class HttpServletRequestImpl
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletOutputStreamImpl.java:[63,20] error: cannot find symbol
[ERROR] symbol: class WriteListener
[ERROR] location: package javax.servlet
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletInputStreamImpl.java:[168,38] error: cannot find symbol
[ERROR] symbol: class ReadListener
[ERROR] location: class ServletInputStreamImpl
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletOutputStreamImpl.java:[150,33] error: cannot find symbol
[ERROR] symbol: class WriteListener
[ERROR] location: class ServletOutputStreamImpl
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletOutputStreamImpl.java:[168,16] error: cannot find symbol
[ERROR] symbol: class WriteListener
[ERROR] location: class ServletOutputStreamImpl.WriteHandlerImpl
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletOutputStreamImpl.java:[170,33] error: cannot find symbol
[ERROR] symbol: class WriteListener
[ERROR] location: class ServletOutputStreamImpl.WriteHandlerImpl
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletInputStreamImpl.java:[178,16] error: cannot find symbol
[ERROR] symbol: class ReadListener
[ERROR] location: class ServletInputStreamImpl.ReadHandlerImpl
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletInputStreamImpl.java:[180,32] error: cannot find symbol
[ERROR] symbol: class ReadListener
[ERROR] location: class ServletInputStreamImpl.ReadHandlerImpl
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/HttpServletRequestImpl.java:[89,25] error: cannot find symbol
[ERROR] symbol: class ProtocolHandler
[ERROR] location: package javax.servlet.http
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletInputStreamImpl.java:[61,20] error: cannot find symbol
[ERROR] symbol: class ReadListener
[ERROR] location: package javax.servlet
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/HttpServletRequestImpl.java:[1588,24] error: cannot find symbol
[ERROR] symbol: class ProtocolHandler
[ERROR] location: class HttpServletRequestImpl
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletOutputStreamImpl.java:[63,20] error: cannot find symbol
[ERROR] symbol: class WriteListener
[ERROR] location: package javax.servlet
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletInputStreamImpl.java:[168,38] error: cannot find symbol
[ERROR] symbol: class ReadListener
[ERROR] location: class ServletInputStreamImpl
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletOutputStreamImpl.java:[150,33] error: cannot find symbol
[ERROR] symbol: class WriteListener
[ERROR] location: class ServletOutputStreamImpl
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletOutputStreamImpl.java:[168,16] error: cannot find symbol
[ERROR] symbol: class WriteListener
[ERROR] location: class ServletOutputStreamImpl.WriteHandlerImpl
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletOutputStreamImpl.java:[170,33] error: cannot find symbol
[ERROR] symbol: class WriteListener
[ERROR] location: class ServletOutputStreamImpl.WriteHandlerImpl
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletInputStreamImpl.java:[178,16] error: cannot find symbol
[ERROR] symbol: class ReadListener
[ERROR] location: class ServletInputStreamImpl.ReadHandlerImpl
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletInputStreamImpl.java:[180,32] error: cannot find symbol
[ERROR] symbol: class ReadListener
[ERROR] location: class ServletInputStreamImpl.ReadHandlerImpl
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/HttpServletRequestImpl.java:[302,4] error: method does not override or implement a method from a supertype
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/HttpServletRequestImpl.java:[1587,4] error: method does not override or implement a method from a supertype
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/HttpServletResponseImpl.java:[275,4] error: method does not override or implement a method from a supertype
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletInputStreamImpl.java:[131,4] error: method does not override or implement a method from a supertype
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletInputStreamImpl.java:[139,4] error: method does not override or implement a method from a supertype
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletInputStreamImpl.java:[167,4] error: method does not override or implement a method from a supertype
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletOutputStreamImpl.java:[121,4] error: method does not override or implement a method from a supertype
[ERROR] /home/gil/rpmbuild/BUILD/grizzly-2.3-beta8/modules/http-servlet/src/main/java/org/glassfish/grizzly/servlet/ServletOutputStreamImpl.java:[149,4] error: method does not override or implement a method from a supertype
[ERROR] -> [Help 1]

thanks

**Comment by glassfishrobot** [comment]
@glassfishrobot Commented 
oleksiys said:
With Grizzly 2.3-beta8 you can use servlet 3.1 beta1 API
[http://search.maven.org/remotecontent?filepath=javax/servlet/javax.servlet-api/3.1-b01/javax.servlet-api-3.1-b01.jar](http://search.maven.org/remotecontent?filepath=javax/servlet/javax.servlet-api/3.1-b01/javax.servlet-api-3.1-b01.jar)

it should be compliant w/ servlet 3.0

Thanks.

WBR.

**Comment by glassfishrobot** [comment]
@glassfishrobot Commented 
puntogil said:
from what You can see^ from the errors does not seem to be conpatibile with servlet 3.0 apis

we DON'T USE (in fedora) non system libraries like
[ftp://mirrors.ibiblio.org/maven2/javax/servlet/javax.servlet-api/3.1-b01/javax.servlet-api-3.1-b01.jar](ftp://mirrors.ibiblio.org/maven2/javax/servlet/javax.servlet-api/3.1-b01/javax.servlet-api-3.1-b01.jar)
in fedora cannot be used
we built ALL java libraries
what is the problem? you can not use a library servlet 3.0?
thanks regards

**Comment by glassfishrobot** [comment]
@glassfishrobot Commented 
oleksiys said:
Well, I meant backward compatibility.
Servlet 3.0 apps. should work with Servlet 3.1 api, which is what you need, right?

You can find 3.1 beta1 API sources and javadocs here:
[http://search.maven.org/#artifactdetails](http://search.maven.org/#artifactdetails)|javax.servlet|javax.servlet-api|3.1-b01|jar

We upgraded our servlet support to Servlet 3.1 API, so servlet 3.0 apps should work as well.

Hope this helps.

Thanks.
WBR

**Comment by glassfishrobot** [comment]
@glassfishrobot Commented 
puntogil said:
yes i meant if possible add backward compatibility.
we cant import javax.servlet|javax.servlet-api|3.1-b01
i already imported javax.servlet|javax.servlet-api|3.1-b02
(with a little patch work fine with Grizzly 2.3-beta8)
but javax.servlet-api|3.1-b02
has not passed the revision due to some problems with others existing servlet-api libraries (3.0)
another problem for us is an existing
[https://svn.java.net/svn/glassfish~svn/tags/javax.servlet-api-3.1-b04/](https://svn.java.net/svn/glassfish~svn/tags/javax.servlet-api-3.1-b04/)
but also seem have some compatibility problems
(we prefer to import the latest version of a library)
but we use only tomcat or jboss apis
thanks regards

this is our dep(endency)map for servlet-api
<dependency>
<maven>
<groupId>org.apache.tomcat</groupId>
<artifactId>tomcat-servlet-api</artifactId>
<version>7.0.33</version>
</maven>
<jpp>
<groupId>JPP</groupId>
<artifactId>tomcat-servlet-api</artifactId>
<version>7.0.33</version>
</jpp>
</dependency>

<dependency>
<maven>
<groupId>javax.servlet</groupId>
<artifactId>servlet-api</artifactId>
<version>7.0.33</version>
</maven>
<jpp>
<groupId>JPP</groupId>
<artifactId>tomcat-servlet-api</artifactId>
<version>7.0.33</version>
</jpp>
</dependency>

<dependency>
<maven>
<groupId>javax.servlet</groupId>
<artifactId>javax.servlet-api</artifactId>
<version>7.0.33</version>
</maven>
<jpp>
<groupId>JPP</groupId>
<artifactId>tomcat-servlet-api</artifactId>
<version>7.0.33</version>
</jpp>
</dependency>

<dependency>
<maven>
<groupId>org.mortbay.jetty</groupId>
<artifactId>servlet-api</artifactId>
<version>7.0.33</version>
</maven>
<jpp>
<groupId>JPP</groupId>
<artifactId>tomcat-servlet-api</artifactId>
<version>7.0.33</version>
</jpp>
</dependency>

<dependency>
<maven>
<groupId>org.jboss.spec.javax.servlet</groupId>
<artifactId>jboss-servlet-api_3.0_spec</artifactId>
<version>1.0.1.Final</version>
</maven>
<jpp>
<groupId>JPP</groupId>
<artifactId>jboss-servlet-3.0-api</artifactId>
<version>1.0.1.Final</version>
</jpp>
</dependency>

<dependency>
<maven>
<groupId>javax.servlet</groupId>
<artifactId>servlet-api</artifactId>
<version>1.0.1.Final</version>
</maven>
<jpp>
<groupId>JPP</groupId>
<artifactId>jboss-servlet-3.0-api</artifactId>
<version>1.0.1.Final</version>
</jpp>
</dependency>

**Comment by glassfishrobot** [comment]
@glassfishrobot Commented 
@rlubke said:
Grizzly 2.3.4 (to be released later this week) is now compatible with the final Servlet 3.1 api bits. This should take care of the problems that were seen. If, after testing 2.3.4, the problem persists, please re-open the issue.

**Comment by glassfishrobot** [comment]
@glassfishrobot Commented 
Marked as **fixed** on Tuesday, July 9th 2013, 9:21:41 am

**Comment by glassfishrobot** [comment]
@glassfishrobot Commented 
This issue was imported from java.net JIRA GRIZZLY-1383

**Comment by glassfishrobot** [comment]
* **Issue Imported From:** https://github.com/javaee/grizzly/issues/1383
* **Original Issue Raised By:**@glassfishrobot
* **Original Issue  Assigned To:** @glassfishrobot
* **Original Issue  Closed By:**@glassfishrobot
